LdapConfig:
    columns:
        host:
            type: string(255)
        port: integer(2)
        accountDomainName:
            type: string(255)
        accountDomainNameShort:
            type: string(255)
        username: 
            type: string(255)
        password: 
            type: string(255)
        baseDn: 
            type: string
        # Account filter is not plaintext purified either, for the reason as the password field      
        accountFilterFormat: 
            type: string(255)
        accountCanonicalForm: string(255)
        bindRequiresDn: boolean
        useSsl: boolean
        useStartTls: boolean
